services: 

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "srvr"
    healthcheck:
      test: ["CMD-SHELL", "echo srvr | nc localhost 2181 | grep Zookeeper"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - service-network
  
  # ================= Kafka =================
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - service-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: erris@dev.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - auth-db
    networks:
      - service-network

  #================= Microservice: Auth Service ==================#
  auth-service:
    container_name: auth-service
    image: authservice
    build:
      context: ./backend/microservices/auth-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./backend/microservices/auth-service:/app
    command: air
    env_file:
      - ./backend/microservices/auth-service/.env
    depends_on:
      - auth-db
    networks:
      - service-network

  auth-db:
    container_name: auth-db
    image: postgres:15
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: auth123
      POSTGRES_DB: authdb
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U authuser -d authdb" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - service-network

  #================= Microservice: Ingest Service ==================#
  ingest-service:
    container_name: ingest-service
    build:
      context: ./backend/microservices/ingest-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/microservices/ingest-service:/app
    env_file:
      - ./backend/microservices/ingest-service/.env
    depends_on:
      - kafka
    networks:
      - service-network

  #================= Microservice: Processing Service ==================#
  processing-service:
    container_name: processing-service
    build:
      context: ./backend/microservices/processing-service
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    volumes:
      - ./backend/microservices/processing-service:/app
    env_file:
      - ./backend/microservices/processing-service/.env
    depends_on:
      - kafka
    networks:
      - service-network

  mongo:
      container_name: mongo
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
      networks:
        - service-network

    # ================= Microservice: Analytical Service =================
  analytical-service:
      container_name: analytical-service
      build:
        context: ./backend/microservices/analytics-service
        dockerfile: Dockerfile
      ports:
        - "4000:4000"
      volumes:
        - ./backend/microservices/analytics-service:/app
        - /app/node_modules # Prevents local node_modules from overwriting container ones
      environment:
        - NODE_ENV=development
        - KAFKA_BROKERS=kafka:29092
        - MONGO_URI=mongodb://mongo:27017/health_db
        - PORT=4000
      env_file:
        - ./backend/microservices/analytics-service/.env
      depends_on:
        - kafka
        - mongo
      networks:
        - service-network

networks:
  service-network:
    driver: bridge
  
volumes:
  pgadmin-data:
  auth-db-data:
  mongo-data: