global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8000']

  - job_name: 'processing-service'
    static_configs:
      - targets: ['processing-service:8000']

  - job_name: 'data-ingestion-service'
    static_configs:
      - targets: ['data-ingestion-service:8000']
